import { jsPDF } from 'jspdf';

/**
 * Parses markdown notes text into a comprehensive structured JSON schema
 */
export function parseNotesToStructuredJson(note = {}) {
  const title = (note.title || 'Untitled Notes').trim();
  const content = (note.content || '').trim();
  const style = note.style || 'Comprehensive Study Notes';
  const depth = note.depth || 'Balanced';
  const topic = note.topic || '';
  const now = new Date().toISOString();

  const lines = content.split('\n');
  const sections = [];
  const keyDefinitions = [];
  const examTakeaways = [];

  let currentSection = {
    heading: 'Introduction / Overview',
    level: 1,
    paragraphs: [],
    items: [],
  };

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    const trimmed = rawLine.trim();

    if (!trimmed) continue;

    // Headings # ## ###
    const headingMatch = trimmed.match(/^(#{1,4})\s+(.+)$/);
    if (headingMatch) {
      if (currentSection.paragraphs.length > 0 || currentSection.items.length > 0) {
        sections.push({
          heading: currentSection.heading,
          level: currentSection.level,
          body: currentSection.paragraphs.join('\n\n'),
          items: currentSection.items,
        });
      }
      currentSection = {
        heading: headingMatch[2].replace(/\*\*/g, '').trim(),
        level: headingMatch[1].length,
        paragraphs: [],
        items: [],
      };
      continue;
    }

    // Bullet points (* or -)
    const bulletMatch = trimmed.match(/^[-*•]\s+(.+)$/);
    if (bulletMatch) {
      const itemText = bulletMatch[1].replace(/\*\*/g, '').trim();
      currentSection.items.push(itemText);

      // Check if definition (e.g. "Term: Explanation")
      const defMatch = itemText.match(/^([A-Za-z0-9\s_-]+?)\s*:\s*(.+)$/);
      if (defMatch && defMatch[1].length < 50) {
        keyDefinitions.push({
          term: defMatch[1].trim(),
          definition: defMatch[2].trim(),
        });
      }

      // Check if takeaway / exam summary
      if (/takeaway|exam|crucial|key\s+point|summary|remember/i.test(currentSection.heading)) {
        examTakeaways.push(itemText);
      }
      continue;
    }

    // Numbered points (1., 2.)
    const numMatch = trimmed.match(/^\d+[\.)]\s+(.+)$/);
    if (numMatch) {
      const itemText = numMatch[1].replace(/\*\*/g, '').trim();
      currentSection.items.push(itemText);
      continue;
    }

    // Regular paragraph
    currentSection.paragraphs.push(trimmed.replace(/\*\*/g, ''));
  }

  // Push final section
  if (currentSection.paragraphs.length > 0 || currentSection.items.length > 0) {
    sections.push({
      heading: currentSection.heading,
      level: currentSection.level,
      body: currentSection.paragraphs.join('\n\n'),
      items: currentSection.items,
    });
  }

  const words = content.split(/\s+/).filter(Boolean).length;

  return {
    schemaVersion: '1.0.0',
    generator: 'SourceWise AI Study Companion',
    exportedAt: now,
    metadata: {
      id: note.id || null,
      title,
      style,
      depth,
      topic,
      wordCount: words,
      characterCount: content.length,
      sectionCount: sections.length,
      createdAt: note.createdAt || now,
      lastModified: note.lastModified || now,
    },
    sections,
    keyDefinitions,
    examTakeaways,
    rawMarkdown: content,
  };
}

/**
 * Downloads notes as a structured .json file
 */
export function exportNotesAsJson(note = {}) {
  const structuredData = parseNotesToStructuredJson(note);
  const jsonString = JSON.stringify(structuredData, null, 2);
  const blob = new Blob([jsonString], { type: 'application/json;charset=utf-8' });
  const filename = `${sanitizeFilename(note.title || 'Study_Notes')}.json`;

  triggerBlobDownload(blob, filename);
  return structuredData;
}

/**
 * Downloads notes as a formatted markdown (.md) file
 */
export function exportNotesAsMarkdown(note = {}) {
  const content = note.content || '';
  const title = note.title || 'Study Notes';
  const header = `# ${title}\n*Generated by SourceWise AI Study Companion • ${new Date().toLocaleDateString()}*\n\n---\n\n`;
  const fullMd = content.startsWith('#') ? content : `${header}${content}`;

  const blob = new Blob([fullMd], { type: 'text/markdown;charset=utf-8' });
  const filename = `${sanitizeFilename(title)}.md`;

  triggerBlobDownload(blob, filename);
}

/**
 * Downloads notes as a styled, publication-ready multi-page .pdf file using jsPDF
 */
export function exportNotesAsPdf(note = {}) {
  const title = (note.title || 'Study Notes').trim();
  const content = (note.content || '').trim();
  const style = note.style || 'Comprehensive Study Notes';
  const depth = note.depth || 'Balanced';
  const topic = note.topic || '';
  const dateStr = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginX = 45;
  const contentWidth = pageWidth - marginX * 2;
  const bottomThreshold = pageHeight - 50;

  let y = 45;

  const checkPageBreak = (neededHeight) => {
    if (y + neededHeight > bottomThreshold) {
      doc.addPage();
      y = 45;
      return true;
    }
    return false;
  };

  // Top Accent Bar (SourceWise Coral)
  doc.setFillColor(232, 132, 95); // #E8845F
  doc.rect(marginX, y, contentWidth, 4, 'F');
  y += 16;

  // Header Subtitle / Branding
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(192, 90, 53); // #C05A35
  doc.text('SOURCEWISE • AI STUDY NOTES & REVISION GUIDE', marginX, y);
  y += 18;

  // Document Main Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(30, 27, 22); // #1E1B16
  const splitTitle = doc.splitTextToSize(title, contentWidth);
  doc.text(splitTitle, marginX, y);
  y += splitTitle.length * 22;

  // Metadata Card / Pill Box
  const metaText = `Topic: ${topic || 'General'}  |  Style: ${style}  |  Level: ${depth}  |  Date: ${dateStr}`;
  doc.setFillColor(250, 248, 245); // #FAF8F5
  doc.setDrawColor(237, 231, 225); // #EDE7E1
  doc.roundedRect(marginX, y, contentWidth, 22, 4, 4, 'FD');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(138, 129, 123); // #8A817B
  doc.text(metaText, marginX + 10, y + 14);
  y += 34;

  // Parse lines for body
  const lines = content.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    const trimmed = rawLine.trim();

    if (!trimmed) {
      y += 6;
      continue;
    }

    // H1 Heading (# Heading)
    const h1Match = trimmed.match(/^#\s+(.+)$/);
    if (h1Match) {
      checkPageBreak(36);
      y += 10;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(192, 90, 53); // Coral Dark #C05A35
      const hText = h1Match[1].replace(/\*\*/g, '').trim();
      const splitH = doc.splitTextToSize(hText, contentWidth);
      doc.text(splitH, marginX, y);
      y += splitH.length * 16 + 4;

      // Thin divider under H1
      doc.setDrawColor(237, 231, 225);
      doc.line(marginX, y, marginX + contentWidth, y);
      y += 10;
      continue;
    }

    // H2 Heading (## Heading)
    const h2Match = trimmed.match(/^##\s+(.+)$/);
    if (h2Match) {
      checkPageBreak(30);
      y += 8;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(30, 27, 22); // Charcoal #1E1B16
      const hText = h2Match[1].replace(/\*\*/g, '').trim();
      const splitH = doc.splitTextToSize(hText, contentWidth);
      doc.text(splitH, marginX, y);
      y += splitH.length * 14 + 6;
      continue;
    }

    // H3 Heading (### Heading)
    const h3Match = trimmed.match(/^###\s+(.+)$/);
    if (h3Match) {
      checkPageBreak(24);
      y += 6;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10.5);
      doc.setTextColor(91, 84, 78); // #5B544E
      const hText = h3Match[1].replace(/\*\*/g, '').trim();
      const splitH = doc.splitTextToSize(hText, contentWidth);
      doc.text(splitH, marginX, y);
      y += splitH.length * 13 + 4;
      continue;
    }

    // Bullet Points (- or * or •)
    const bulletMatch = trimmed.match(/^[-*•]\s+(.+)$/);
    if (bulletMatch) {
      const cleanBullet = bulletMatch[1].replace(/\*\*/g, '').trim();
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9.5);
      doc.setTextColor(43, 39, 35); // #2B2723

      const bulletIndent = 14;
      const bulletContentWidth = contentWidth - bulletIndent;
      const wrapped = doc.splitTextToSize(cleanBullet, bulletContentWidth);
      const neededHeight = wrapped.length * 13 + 3;

      checkPageBreak(neededHeight);

      // Bullet dot in coral accent
      doc.setFillColor(232, 132, 95);
      doc.circle(marginX + 5, y - 3, 2, 'F');

      doc.text(wrapped, marginX + bulletIndent, y);
      y += neededHeight;
      continue;
    }

    // Numbered Points (1. 2.)
    const numMatch = trimmed.match(/^(\d+[\.)])\s+(.+)$/);
    if (numMatch) {
      const numPrefix = numMatch[1];
      const cleanText = numMatch[2].replace(/\*\*/g, '').trim();
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9.5);
      doc.setTextColor(43, 39, 35);

      const numIndent = 18;
      const numContentWidth = contentWidth - numIndent;
      const wrapped = doc.splitTextToSize(cleanText, numContentWidth);
      const neededHeight = wrapped.length * 13 + 3;

      checkPageBreak(neededHeight);

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(192, 90, 53);
      doc.text(numPrefix, marginX, y);

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(43, 39, 35);
      doc.text(wrapped, marginX + numIndent, y);
      y += neededHeight;
      continue;
    }

    // Regular text paragraph
    const cleanParagraph = trimmed.replace(/\*\*/g, '').trim();
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(43, 39, 35);

    const wrapped = doc.splitTextToSize(cleanParagraph, contentWidth);
    const neededHeight = wrapped.length * 13 + 5;

    checkPageBreak(neededHeight);
    doc.text(wrapped, marginX, y);
    y += neededHeight;
  }

  // Footer on all pages: Page X of Total
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);

    // Divider line above footer
    doc.setDrawColor(237, 231, 225);
    doc.line(marginX, pageHeight - 35, marginX + contentWidth, pageHeight - 35);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(138, 129, 123);
    doc.text('SourceWise AI Study Companion • Auto-generated Study Notes', marginX, pageHeight - 22);

    const pageNumText = `Page ${p} of ${totalPages}`;
    doc.text(pageNumText, pageWidth - marginX - doc.getTextWidth(pageNumText), pageHeight - 22);
  }

  const filename = `${sanitizeFilename(title)}.pdf`;
  doc.save(filename);
}

/**
 * Clean string for safe file naming
 */
function sanitizeFilename(str) {
  return str
    .replace(/[^a-zA-Z0-9_\-\s]/g, '')
    .trim()
    .replace(/\s+/g, '_')
    .slice(0, 50) || 'Study_Notes';
}

/**
 * Triggers a file download in the browser
 */
function triggerBlobDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
