/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms';

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#fbf8ff",
        foreground: "hsl(var(--foreground))",
        // Ninefold Brand & Design System Colors
        primary: {
          DEFAULT: "#9a442d",
          foreground: "#ffffff",
        },
        "primary-container": "#e07a5f",
        "on-primary": "#ffffff",
        "on-primary-container": "#5b1604",
        "primary-fixed": "#ffdbd2",
        "primary-fixed-dim": "#ffb4a1",
        "on-primary-fixed": "#3c0800",
        "on-primary-fixed-variant": "#7c2e19",
        "inverse-primary": "#ffb4a1",
        secondary: {
          DEFAULT: "#9c4141",
          foreground: "#ffffff",
        },
        "secondary-container": "#fe8e8b",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#762527",
        "secondary-fixed": "#ffdad8",
        "secondary-fixed-dim": "#ffb3b0",
        "on-secondary-fixed": "#410006",
        "on-secondary-fixed-variant": "#7d2a2c",
        tertiary: {
          DEFAULT: "#57615c",
          foreground: "#ffffff",
        },
        "tertiary-container": "#8f9994",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#28312d",
        "tertiary-fixed": "#dbe5df",
        "tertiary-fixed-dim": "#bfc9c3",
        "on-tertiary-fixed": "#151d1a",
        "on-tertiary-fixed-variant": "#3f4945",
        surface: "#fbf8ff",
        "surface-dim": "#d7d8f4",
        "surface-bright": "#fbf8ff",
        "surface-variant": "#e0e0fc",
        "surface-tint": "#9a442d",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f2ff",
        "surface-container": "#edecff",
        "surface-container-high": "#e6e6ff",
        "surface-container-highest": "#e0e0fc",
        "on-surface": "#181a2e",
        "on-surface-variant": "#55423e",
        "inverse-surface": "#2d2f44",
        "inverse-on-surface": "#f1efff",
        outline: "#88726d",
        "outline-variant": "#dbc1ba",
        "on-background": "#181a2e",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        wood: {
          dark: '#5C3D2E',
          DEFAULT: '#8B5E3C',
          light: '#B8860B',
        },
        parchment: {
          dark: '#E8D4B8',
          DEFAULT: '#F5E6C8',
          light: '#FFF8DC',
        },
        amber: {
          warm: '#FFB347',
          gold: '#DAA520',
        },
        copper: '#B87333',
        sage: '#8FBC8F',
        moss: '#6B8E23',
        // ── SourceWise unified brand system (coral + light neutrals) ──
        coral: {
          DEFAULT: '#E8845F',
          dark: '#D96F4A',
          deep: '#C05A35',
          soft: '#FDEEE6',
        },
        ink: '#1E1B16',
        body: '#5B544E',
        faint: '#8A817B',
        line: '#EDE7E1',
        sidebar: '#FAFAFA',
        canvas: '#FFFDFB',
        teal: {
          DEFAULT: '#0F766E',
          soft: '#E0F2F0',
        },
        amberbrand: {
          DEFAULT: '#D97706',
          soft: '#FEF3E2',
        },
        // ── Subject palette (mirrors planner/utils/subjectPalette + backend SUBJECT_COLORS) ──
        subject: {
          bio: { DEFAULT: '#0F766E', soft: '#E0F2F0' },
          chem: { DEFAULT: '#D97706', soft: '#FEF3E2' },
          phys: { DEFAULT: '#7C3AED', soft: '#F1E9FF' },
          math: { DEFAULT: '#E8845F', soft: '#FDEEE6' },
          hist: { DEFAULT: '#8B5E3C', soft: '#F5E6C8' },
          lit: { DEFAULT: '#9C4141', soft: '#FFDAD8' },
          lang: { DEFAULT: '#57615C', soft: '#DBE5DF' },
          cs: { DEFAULT: '#1E1B16', soft: '#EDE7E1' },
          econ: { DEFAULT: '#047857', soft: '#D1FAE5' },
          art: { DEFAULT: '#DB2777', soft: '#FCE7F3' },
        },
      },
      spacing: {
        "space-4xl": "6rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-2xl": "3rem",
        "space-lg": "1.5rem",
        "margin-desktop": "3.5rem",
        "space-3xl": "4rem",
        "space-xl": "2rem",
        "gutter-desktop": "2rem",
        "margin-tablet": "2rem",
        "space-md": "1rem",
        "space-2xs": "0.25rem",
        "margin-mobile": "1rem",
      },
      borderRadius: {
        lg: "2rem",
        md: "1.5rem",
        sm: "0.5rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        display: ['Epilogue', 'Playfair Display', 'serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', '"Cascadia Code"', 'Consolas', 'Menlo', 'Monaco', '"Source Code Pro"', 'monospace'],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Epilogue", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Epilogue", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Epilogue", "sans-serif"],
        "headline-xl": ["Epilogue", "sans-serif"],
        "display-hero": ["Epilogue", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Epilogue", "sans-serif"],
        "headline-sm": ["Epilogue", "sans-serif"],
      },
      fontSize: {
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-hero": ["56px", { lineHeight: "68px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["17px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
      },
      boxShadow: {
        'card': '0 1px 2px rgba(30,27,22,0.04), 0 8px 24px -12px rgba(30,27,22,0.12)',
        'card-hover': '0 2px 4px rgba(30,27,22,0.05), 0 16px 32px -12px rgba(232,132,95,0.22)',
        'warm-sm': '0 2px 8px rgba(139, 69, 19, 0.08)',
        'warm': '0 4px 16px rgba(139, 69, 19, 0.12)',
        'warm-md': '0 6px 24px rgba(139, 69, 19, 0.15)',
        'warm-lg': '0 12px 40px rgba(139, 69, 19, 0.18)',
        'candle': '0 0 30px rgba(255, 179, 71, 0.25)',
        'candle-lg': '0 0 50px rgba(255, 179, 71, 0.35)',
        'lamp': '0 8px 32px rgba(218, 165, 32, 0.15)',
        'paper': '0 1px 3px rgba(139, 69, 19, 0.1), 0 1px 2px rgba(139, 69, 19, 0.06)',
        'paper-hover': '0 8px 25px rgba(139, 69, 19, 0.15), 0 3px 10px rgba(139, 69, 19, 0.08)',
        'inner': 'inset 0 2px 8px 0 rgba(0, 0, 0, 0.06)',
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.7s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in': 'fadeIn 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-in-right': 'slideInRight 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-in-left': 'slideInLeft 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'pulse': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-subtle': 'bounceSubtle 3s ease-in-out infinite',
        'shimmer': 'shimmer 3s linear infinite',
        'float': 'float 8s ease-in-out infinite',
        'scale-in': 'scaleIn 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'flicker': 'flicker 3s ease-in-out infinite',
        'breathe': 'breathe 4s ease-in-out infinite',
        'paper-float': 'paperFloat 6s ease-in-out infinite',
        'glow-pulse': 'glowPulse 2s ease-in-out infinite',
        'book-open': 'bookOpen 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'page-turn': 'pageTurn 0.6s ease-in-out',
        'candle-dance': 'candleDance 2s ease-in-out infinite',
        'dust-float': 'dustFloat 20s linear infinite',
        'warm-pulse': 'warmPulse 2s ease-in-out infinite',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(40px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-40px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        bounceSubtle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-15px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-25px)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        flicker: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.85' },
          '25%': { opacity: '0.95' },
          '75%': { opacity: '0.9' },
        },
        breathe: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.8' },
          '50%': { transform: 'scale(1.02)', opacity: '1' },
        },
        paperFloat: {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '33%': { transform: 'translateY(-10px) rotate(1deg)' },
          '66%': { transform: 'translateY(-5px) rotate(-1deg)' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(255, 179, 71, 0.2)' },
          '50%': { boxShadow: '0 0 40px rgba(255, 179, 71, 0.4)' },
        },
        bookOpen: {
          '0%': { transform: 'rotateY(-90deg)', opacity: '0' },
          '100%': { transform: 'rotateY(0)', opacity: '1' },
        },
        pageTurn: {
          '0%': { transform: 'rotateY(0)' },
          '50%': { transform: 'rotateY(-10deg)' },
          '100%': { transform: 'rotateY(0)' },
        },
        candleDance: {
          '0%, 100%': { transform: 'translateX(0) scaleY(1)' },
          '25%': { transform: 'translateX(1px) scaleY(1.02)' },
          '50%': { transform: 'translateX(-1px) scaleY(0.98)' },
          '75%': { transform: 'translateX(0.5px) scaleY(1.01)' },
        },
        dustFloat: {
          '0%': { transform: 'translateY(100vh) translateX(0)', opacity: '0' },
          '10%': { opacity: '0.6' },
          '90%': { opacity: '0.6' },
          '100%': { transform: 'translateY(-100vh) translateX(100px)', opacity: '0' },
        },
        warmPulse: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(255, 179, 71, 0.4)' },
          '50%': { boxShadow: '0 0 0 10px rgba(255, 179, 71, 0)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'shimmer': 'linear-gradient(90deg, transparent, rgba(255,255,255,0.1), transparent)',
        'parchment': 'linear-gradient(135deg, #F5E6C8 0%, #FAEBD7 50%, #FFF8DC 100%)',
        'wood': 'linear-gradient(180deg, #5C3D2E 0%, #8B5E3C 100%)',
        'warm': 'linear-gradient(135deg, #FFB347 0%, #DAA520 100%)',
      }
    },
  },
  plugins: [
    forms,
  ],
}
